import './globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import Header from '../components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        {/* ✅ Correct way to load external scripts in Next.js */}
        <Script
          src="https://cdn.tailwindcss.com/3.4.16"
          strategy="beforeInteractive"
        />
        <Header />
        {children}
      </body>
    </html>
  )
}
